version: '3'

services:
    db:
        image: postgres
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    exam:
        build: .
        command: daphne -p 8080 --access-log - /opt/immfly-dockerize/immfly.asgi:application
        volumes:
            - ./immfly:/opt/immfly-dockerize
        ports:
            - "8080:8080"
        depends_on: 
            - db
        links:
            - db:db
