# Generated by Django 3.0.3 on 2020-02-28 15:19

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.FileField(upload_to='')),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rating_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator('0.0'), django.core.validators.MaxValueValidator('10.0')])),
            ],
        ),
        migrations.CreateModel(
            name='TreeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('root', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='channel.ChannelNode')),
            ],
        ),
        migrations.AddField(
            model_name='channelnode',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Content'),
        ),
        migrations.AddField(
            model_name='channelnode',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Language'),
        ),
        migrations.AddField(
            model_name='channelnode',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='channel.ChannelNode'),
        ),
    ]
