# Generated by Django 3.0.3 on 2020-03-03 12:48

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, height_field=100, upload_to='', width_field=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Language')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='channel.ChannelNode')),
            ],
        ),
        migrations.CreateModel(
            name='TreeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.FileField(blank=True, upload_to='')),
                ('meta_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rating_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='channel.ChannelNode')),
            ],
        ),
        migrations.AddField(
            model_name='channelnode',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='channel.TreeChannel'),
        ),
    ]
