# Generated by Django 3.0.3 on 2020-02-28 15:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20200228_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rating_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=2, validators=[django.core.validators.MinValueValidator('0.00'), django.core.validators.MaxValueValidator('10.00')]),
        ),
    ]
