# Generated by Django 3.0.3 on 2020-02-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20200228_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelnode',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channel.Content'),
        ),
    ]
