# Generated by Django 3.0.3 on 2020-03-01 23:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20200228_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelnode',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='treechannel',
            name='root',
        ),
        migrations.AddField(
            model_name='channelnode',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='channel.TreeChannel'),
        ),
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='channel.ChannelNode'),
        ),
        migrations.AlterField(
            model_name='channelnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='channel.ChannelNode'),
        ),
        migrations.AlterField(
            model_name='channelnode',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='channelnode',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field=100, upload_to='', width_field=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
    ]
